### Homework Linear Regression
The dataset you are working is Boston Housing Price

The Boston_Housing_Prices dataset is a famous dataset usually used for learning or benchmarking regression techniques. This dataset contains 14 variables, one of which (MEDV, median value of home) we'll use as the target.


1- Read in the dataset using sklearn's load_boston() function (found in sklearn.datasets)


2- Perform some basic exploratory data analysis to get a feel for the data. Graph some stuff!


3- Create a correlation heatmap to check to see how highly correlated our predictor variables (features) are (Remember, if our predictors are highly correlated, this is bad.)


4- Train the model based on the train set. Use 75 percent of the data for train part. Use 25 percent of the data for test part.

Hint: from sklearn.model_selection import train_test_split
Hint: X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)


5 -Make predictions on your test set (X_test) and see how well it compares to the actual targets (y_test) from the test set.


6- Compute, Mean-Square-Error (MSE) and R Squared score of your Model

In [2]:
#import dependencies
import pandas as pd 
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [3]:
#load the Boston Housing Data set from sklearn.datasets 
from sklearn.datasets import load_boston

boston = load_boston()

print(boston.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [4]:
print(boston.data.shape)

(506, 13)


In [5]:
#turn data set into data frame 
#data = x values, the independent variables 
#feature_names = column names of the data 
#target = y value, target variable ~ the price of the houses or dependent variable


bost = pd.DataFrame(boston.data)
bost.columns = boston.feature_names
bost['PRICE'] = boston.target

bost.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [6]:
df_x = pd.DataFrame(boston.data, columns= boston.feature_names)
df_y = pd.DataFrame(boston.target)

In [7]:
#statistics from data set 
df_x.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [8]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np 

#calculate the correlation matrix
corr = bost.corr()

# plot the heatmap
sns.heatmap(corr,
    xticklabels=corr.columns,
    yticklabels=corr.columns
)

In [9]:
#initialize linear regression model 
reg = linear_model.LinearRegression()

In [10]:
#split the data into 75% training and 25% testing data 
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.25, random_state = 0)

In [11]:
#train model with data 
reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
#print coefficient/weights for each feature/column of model 
print(reg.coef_)

[[-1.17735289e-01  4.40174969e-02 -5.76814314e-03  2.39341594e+00
  -1.55894211e+01  3.76896770e+00 -7.03517828e-03 -1.43495641e+00
   2.40081086e-01 -1.12972810e-02 -9.85546732e-01  8.44443453e-03
  -4.99116797e-01]]


In [13]:
#print the predictions on our test data 
y_pred = reg.predict(x_test)
print(y_pred)

[[24.95233283]
 [23.61699724]
 [29.20588553]
 [11.96070515]
 [21.33362042]
 [19.46954895]
 [20.42228421]
 [21.52044058]
 [18.98954101]
 [19.950983  ]
 [ 4.92468244]
 [16.09694058]
 [16.93599574]
 [ 5.33508402]
 [39.84434398]
 [32.33549843]
 [22.32772572]
 [36.54017819]
 [31.03300611]
 [23.32172503]
 [24.92086498]
 [24.26106474]
 [20.71504422]
 [30.45072552]
 [22.45009234]
 [ 9.87470006]
 [17.70324412]
 [17.974775  ]
 [35.69932012]
 [20.7940972 ]
 [18.10554174]
 [17.68317865]
 [19.71354713]
 [23.79693873]
 [29.06528958]
 [19.23738284]
 [10.97815878]
 [24.56199978]
 [17.32913052]
 [15.20340817]
 [26.09337458]
 [20.87706795]
 [22.26187518]
 [15.32582693]
 [22.85847963]
 [25.08887173]
 [19.74138819]
 [22.70744911]
 [ 9.66708558]
 [24.46175926]
 [20.72654169]
 [17.52545047]
 [24.45596997]
 [30.10668865]
 [13.31250981]
 [21.52052342]
 [20.65642932]
 [15.34285652]
 [13.7741129 ]
 [22.07429287]
 [17.53293957]
 [21.60707766]
 [32.91050188]
 [31.32796114]
 [17.64346364]
 [32.69909854]
 [18.56579

In [14]:
#compare above from actual values below
#print the actual values
print(y_test)

        0
329  22.6
371  50.0
219  23.0
403   8.3
78   21.2
..    ...
49   19.4
498  21.2
309  20.3
124  18.8
306  33.4

[127 rows x 1 columns]


In [15]:
#check the model performance ~ accuracy of the model using Mean Squared Error (MSE)
print(np.mean(y_pred - y_test)**2)

0    0.244084
dtype: float64


In [16]:
#another way to check performance using sklearn.metrics 
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_pred, y_test))

29.78224509230252


#### Apply data normalization (Scaling) to improve the prediction result

Use StandardScaler and then train your Linear Regression Model. Compare the R Square score with previous one you got

Use MinMaxScaler and then train your Linear Regression Model. Compare the R Square score with previous one you got

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import time

In [18]:
#helper functions 
def timer(f):
    start = time.time()
    res = f()
    end = time.time()
    return res 

def build_model_for_data(data, target):
    X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=0)
    pipeline = make_pipeline(LinearRegression())
    model = timer(lambda: pipeline.fit(X_train, y_train))
    return (X_test, y_test, model)

In [19]:
#load data
boston = load_boston()

In [20]:
#data set characteristics 
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [21]:
#print value distributions

#example value distribution of features 
for x in boston['data'][0]:
    print(x)

X_test, y_test, model = build_model_for_data(boston['data'], boston['target'])
prediction = model.predict(X_test)
print(mean_squared_error(y_test, prediction))

0.00632
18.0
2.31
0.0
0.538
6.575
65.2
4.09
1.0
296.0
15.3
396.9
4.98
29.78224509230252


In [22]:
#value distributions after min max 
min_max = MinMaxScaler()
boston_min_max = min_max.fit_transform(boston['data'])

for x in boston_min_max[0]:
    print(x)
X_test, y_test, model = build_model_for_data(boston_min_max, boston['target'])
prediction = model.predict(X_test)
print(mean_squared_error(y_test, prediction))

0.0
0.18
0.06781524926686218
0.0
0.31481481481481477
0.5775052692086607
0.6416065911431514
0.26920313906646415
0.0
0.20801526717557245
0.2872340425531916
0.9999999999999999
0.08967991169977926
29.782245092302418


In [23]:
#value distribution after std
std = StandardScaler()
boston_std = std.fit_transform(boston['data'])


for x in boston_std[0]:
    print(x)
X_test, y_test, model = build_model_for_data(boston_min_max, boston['target'])
prediction = model.predict(X_test)
print(mean_squared_error(y_test, prediction))

-0.4197819386460084
0.2848298609673567
-1.2879094989577484
-0.2725985670699254
-0.14421743255530006
0.4136718893017465
-0.1200134161980508
0.1402136034929299
-0.9828428567665046
-0.6666082090210975
-1.4590003802772087
0.44105193260704206
-1.075562304567866
29.782245092302418
