# Scaling, Normalization, One-hot encoding, Label encoding


In [39]:
import numpy as np 

In [40]:
X = np.array([[1000, 2], [1500, 3]])

print(X)
print(X.shape)
print(X[:, 0])
print(X[:, 1])

[[1000    2]
 [1500    3]]
(2, 2)
[1000 1500]
[2 3]


In [41]:
#function will take the X(as input argument of the function is a Numpy array) and returns the scaled version of X 

In [33]:
import numpy as np

def max_min_s(X):
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

X_train = np.array([[1000, 2], [1500, 3]])
print(max_min_s(X_train))

[[0. 0.]
 [1. 1.]]


In [34]:
from sklearn import preprocessing 

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X_train)
print(X_minmax)

[[0. 0.]
 [1. 1.]]


In [35]:
# A two dimensional array (matrix) X is given,  write a function that:
#     subtract the mean element of each column from all the elements of that column 
#     divide the result to the standard deviation of value for each column 

In [36]:
import numpy as np

def standard_s(X):
    return (X - X.mean(axis=0)) / X.std(axis=0)

print(standard_s(X_train))

[[-1. -1.]
 [ 1.  1.]]


In [37]:
standard_scaler = preprocessing.StandardScaler()
X_ss= standard_scaler.fit_transform(X_train)
print(X_ss)

[[-1. -1.]
 [ 1.  1.]]


In [38]:
import numpy as np
X_train = np.array([[ 1., -1.,  2.], [ 2.,  0.,  0.], [ 0.,  1., -1.]])
(X_train[:,0]-X_train[:,0].mean())/X_train[:,0].std()
(X_train[:,1]-X_train[:,1].mean())/X_train[:,1].std()
(X_train[:,2]-X_train[:,2].mean())/X_train[:,2].std()
(X_train-X_train.mean(axis=0))/X_train.std(axis=0)


X_test = [[-1., 1., 0.]]
(-1 - X_train[:,0].mean())/X_train[:,0].std()
(1 - X_train[:,1].mean())/X_train[:,1].std()
(0 - X_train[:,2].mean())/X_train[:,2].std()

# How preprocessing.MinMaxScaler() works
# (X_train - X_train.min(axis=0)) / (X_train.max(axis=0) - X_train.min(axis=0)

-0.2672612419124244